
<!-- Write a SQL query to retrieve all the customer information along with the total number of orders placed by each customer. Display the result in descending order of the number of orders. -->

SELECT c.id , c.name,c.email, c.location ,COUNT(o.id) AS order_items 
FROM customers c
LEFT JOIN orders o ON c.id = o.customer_id
GROUP BY c.id , c.name,c.email, c.location
ORDER BY order_items DESC;

<!-- Write a SQL query to retrieve the product name, quantity, and total amount for each order item. Display the result in ascending order of the order ID. -->

SELECT p.name, oi.quantity,oi.unit_price, oi.quantity * oi.unit_price as total_amount FROM order_items oi 
INNER JOIN products p ON oi.product_id = p.id
ORDER BY order_id ASC;

<!-- Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue. -->

SELECT c.name AS category_name, SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_Items oi
JOIN products p ON oi.product_id = p.id
JOIN categories c ON p.category_id = c.id
GROUP BY c.name
ORDER BY total_revenue DESC;

<!-- Write a SQL query to retrieve the top 5 customers who have made the highest total purchase amount. Display the customer name along with the total purchase amount in descending order of the purchase amount. -->

SELECT c.name AS customer_name, SUM(oi.quantity * oi.unit_price) AS total_purchase_amount
FROM Customers c
JOIN Orders o ON c.id = o.customer_id
JOIN Order_Items oi ON o.id = oi.order_id
GROUP BY c.id
ORDER BY total_purchase_amount DESC
LIMIT 5;



